import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/about.module.css'
import Footer from '../components/Footer'

const About: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>About | Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&display=swap" rel="stylesheet"/> 
      </Head>
      <Header openProjects={()=>{}} />
      <main className={`${styles.mainContent} centerContainer`}>
          
          <section className={styles.contentBlock}>
              <img src="https://ik.imagekit.io/lrjseyuxi3m/todoapp/undraw_checklist__re_2w7v_1_EBpT5tUGgO.png?updatedAt=1636555587766" alt="" />
              <div className={styles.textBlock}>
                <h2>Sobre este projeto</h2>
                <p>Este projeto é parte do meu <b><a href="https://patrickrios.github.io">portfólio</a></b> e foi desenvolvido para fins de <b>estudos</b>. Com ele, eu aprendi novas <b>tecnologias</b> e <b>ferramentas</b> e procurei aprimorar minhas habilidades de programação <b>frontend</b> e <b>UI design</b>.</p>
              </div>
            </section>

            <section className={styles.contentBlock}>
              <div className={styles.textBlock}>
                <h2>Tecnologias usadas</h2>
                <p>A principal <b>ferramenta</b> por trás deste projeto é framework <b><a href="https://nextjs.org/">Next.JS</a></b>, este adiciona uma camada ao framework <b><a href="https://reactjs.org/">ReactJS</a></b> que contém recursos úteis de renderização, rotas e comsumo de API.</p>
                <ul className={styles.textList}>
                  <h3>Alguns recursos usados</h3>
                  <li>
                    <a href="https://pt-br.reactjs.org/docs/context.html">
                      Context api
                    </a>
                    <span>(compartilhar recursos entre páginas e componentes)</span>
                  </li>
                  <li>
                    <a href="https://github.com/css-modules/css-modules">
                      CSS Modules
                    </a>
                  </li>
                  <li>
                    <a href="https://www.emailjs.com/">
                      EmailJS
                    </a>
                    <span>(envio de email para o autor)</span>
                  </li>
                  <li>
                    <a href="https://www.framer.com/motion/">
                      Framer Motion
                    </a>
                    <span>(animações)</span>
                  </li>
                  <li>
                    <a href="https://react-hook-form.com/">
                      React Hook Form
                    </a>
                    <span>(manipular formulários)</span>
                  </li>
                </ul>
                <p>Para o projeto de <b>design de interface</b> eu utilizei a ferramenta <b><a href="https://www.figma.com/">FIGMA</a></b>, na qual criei este <b>protótipo interativo</b>.</p>
              </div>
              <img src="https://ik.imagekit.io/lrjseyuxi3m/todoapp/undraw_web_tech_xbG0aEh3UfI.png?updatedAt=1636583164512" alt="" />
            </section>

      </main>
      <Footer/>
    </div>
  )
}

export default About
